"""
Django settings for yazisleri1 project.

Generated by 'django-admin startproject' using Django 5.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-+w^zij79$iyl4v3$nthk!r$c@1m%%ntfm0vy+@kd10vd7$#@80'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# settings.py

ALLOWED_HOSTS = ['gorevdeyukselmeyaziislerimudur.pythonanywhere.com', 'www.gorevdeyukselmeyaziislerimudur.pythonanywhere.com']



# Application definition

INSTALLED_APPS = [
	'onsayfa.apps.OnsayfaConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'user.apps.UserConfig',

]

# settings.py

SESSION_COOKIE_AGE = 3600  # 1 saat (saniye cinsinden)
SESSION_COOKIE_NAME = 'sessionid'
SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # Oturum, tarayıcı kapatıldığında sona ersin


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]


ROOT_URLCONF = 'yaziisleri1.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'yaziisleri1.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'tr'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
if DEBUG:
    # Geliştirme ortamında statik dosyaları sunmak için
    STATICFILES_DIRS = [
        BASE_DIR / 'static',
    ]
else:
    # Üretim ortamında kullanılacak statik dosya kök dizini
    STATIC_ROOT = BASE_DIR / 'staticfiles'
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# settings.py

# settings.py



# E-posta gönderiminde kullanılacak şablonları belirtin
PASSWORD_RESET_TIMEOUT_DAYS = 1

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  # gmail SMTP sunucusu adresi
EMAIL_PORT = 587  # Hotmail SMTP sunucusunun port numarası genellikle 587'dir
EMAIL_USE_TLS = True  # TLS (Transport Layer Security) kullanılıyor mu?

EMAIL_HOST_USER = 'garibanspider@gmail.com'  # Hotmail SMTP sunucusuna giriş yapacak e-posta adresi
EMAIL_HOST_PASSWORD = 'uovw celj ybey vkpx'  # Hotmail SMTP sunucusuna giriş yapacak şifre
DEFAULT_FROM_EMAIL = 'GOREVDEYUKSELMEYAZİİSLERİMUDUR <garibanspider@gmail.com>'


APPEND_SLASH = True

LOGIN_URL = '/user/login/'  # senin login view'unun URL’si

USE_TZ = False
TIME_ZONE = 'Europe/Istanbul'


