

from django.urls import path
from .import views

# http://127.0.0.1:8000/index

urlpatterns = [
    path('', views.onindex, name='onindex'),                                   # onsayfa urls indeyiz ya bu uygulamanın views klasörüne git  '' boş ise index fonksiyonunu
	path('hakkimizda', views.hakkimizda, name='hakkimizda'),               # hakkimizda ise   hakkimizda fonksiyonunu çalıştır
	path('ornek1',  views.ornek1, name='ornek1'),
	path('index',  views.index, name='index'),
	path('turkce',  views.turkce, name='turkce'),
	path('yetki',  views.yetki, name='yetki'),
	path('anayasa1',  views.anayasa1, name='anayasa1'),
    path('devletintemelorg',  views.devletintemelorg, name='devletintemelorg'),
    path('anayasaNot',  views.anayasaNot, name='anayasaNot'),
    path('turkıyebmm',  views.turkıyebmm, name='turkıyebmm'),
    path('inkilapTarihi',  views.inkilapTarihi, name='inkilapTarihi'),
    path('ulusalGuvenlik',  views.ulusalGuvenlik, name='ulusalGuvenlik'),
    path('KAMUiktisatitesebbusleri',  views.KAMUiktisatitesebbusleri, name='KAMUiktisatitesebbusleri'),
    path('devlettescum1kar',  views.devlettescum1kar, name='devlettescum1kar'),
    path('ilidaresi',  views.ilidaresi, name='ilidaresi'),
    path('ilozelidaresi',  views.ilozelidaresi, name='ilozelidaresi'),
    path('belediyekanunu',  views.belediyekanunu, name='belediyekanunu'),
    path('buyuksehir',  views.buyuksehir, name='buyuksehir'),
    path('devletmemuru657',  views.devletmemuru657, name='devletmemuru657'),
    path('dmksureler',  views.dmksureler, name='dmksureler'),
    path('halklailiskiler',  views.halklailiskiler, name='halklailiskiler'),
    path('etik',  views.etik, name='etik'),
    path('bakanlıkmerkez',  views.bakanlıkmerkez, name='bakanlıkmerkez'),
    path('adaletKomisyonlarınnYapısı',  views.adaletKomisyonlarınnYapısı, name='adaletKomisyonlarınnYapısı'),
    path('ulusalYargıAgıBilisim',  views.ulusalYargıAgıBilisim, name='ulusalYargıAgıBilisim'),
    path('maliYonetim5018',  views.maliYonetim5018, name='maliYonetim5018'),
    path('noluCumhur',  views.noluCumhur, name='noluCumhur'),
    path('genelge154',  views.genelge154, name='genelge154'),
    path('genelge124',  views.genelge124, name='genelge124'),
    path('genelge16',  views.genelge16, name='genelge16'),
    path('genelge161',  views.genelge161, name='genelge161'),
    path('genelge128',  views.genelge128, name='genelge128'),
    path('genelge63',  views.genelge63, name='genelge63'),
    path('genelge630',  views.genelge630, name='genelge630'),
    path('genelge69',  views.genelge69, name='genelge69'),
    path('genelge690',  views.genelge690, name='genelge690'),
    path('genelge104',  views.genelge104, name='genelge104'),
    path('genelge107',  views.genelge107, name='genelge107'),
    path('genelge109',  views.genelge109, name='genelge109'),
    path('genelge168',  views.genelge168, name='genelge168'),
    path('genelge79',  views.genelge79, name='genelge79'),
    path('yargikolları',  views.yargikolları, name='yargikolları'),
    path('adliye5235',  views.adliye5235, name='adliye5235'),
	path('idare2576',  views.idare2576, name='idare2576'),
    path('onuncukısım',  views.onuncukısım, name='onuncukısım'),
    path('imza5070',  views.imza5070, name='imza5070'),
    path('hukukmuh445',  views.hukukmuh445, name='hukukmuh445'),
    path('ceza38a',  views.ceza38a, name='ceza38a'),
    path('bam5madde',  views.bam5madde, name='bam5madde'),
    path('bim5madd',  views.bim5madd, name='bim5madd'),
    path('segbis',  views.segbis, name='segbis'),
    path('tebkveeleki',  views.tebkveeleki, name='tebkveeleki'),
    path('resmiyazısma',  views.resmiyazısma, name='resmiyazısma'),
    path('tebligatkanunu',  views.tebligatkanunu, name='tebligatkanunu'),
    path('tebligatyonetmelik',  views.tebligatyonetmelik, name='tebligatyonetmelik'),
    path('elektroniktebligatyonetmelik',  views.elektroniktebligatyonetmelik, name='elektroniktebligatyonetmelik'),
    path('baslangıc4721',  views.baslangıc4721, name='baslangıc4721'),
    path('kısım4721',  views.kısım4721, name='kısım4721'),
    path('Altıyuzseksenuc4721',  views.Altıyuzseksenuc4721, name='Altıyuzseksenuc4721'),
    path('cezakanunu5237',  views.cezakanunu5237, name='cezakanunu5237'),
    path('idariyargılama2577',  views.idariyargılama2577, name='idariyargılama2577'),
    path('kısım6100',  views.kısım6100, name='kısım6100'),
    path('kısım5271',  views.kısım5271, name='kısım5271'),
    path('adaletbakanlıgıdisiplin',  views.adaletbakanlıgıdisiplin, name='adaletbakanlıgıdisiplin'),
    path('idarisüreler',  views.idarisüreler, name='idarisüreler'),
    path('cezakanunu5271',  views.cezakanunu5271, name='cezakanunu5271'),
    path('harclarkanunu492',  views.harclarkanunu492, name='harclarkanunu492'),
    path('bamhizmetleri',  views.bamhizmetleri, name='bamhizmetleri'),
    path('bimhizmetleri',  views.bimhizmetleri, name='bimhizmetleri'),
    path('bamkayıtlar',  views.bamkayıtlar, name='bamkayıtlar'),
    path('hukukmuhakemesi6100',  views.hukukmuhakemesi6100, name='hukukmuhakemesi6100'),
    path('süreler',  views.süreler, name='süreler'),
    path('infaz5275',  views.infaz5275, name='infaz5275'),
	path('darisüreler',  views.darisüreler, name='darisüreler'),
	path('bim5mad',  views.bim5mad, name='bim5mad'),
	path('sorucoz',  views.sorucoz, name='sorucoz'),
	path('denebakem',  views.denebakem, name='denebakem'),
	path('sorular/', views.sorular, name='sorular'),
	path('bilgiedin',  views.bilgiedin, name='bilgiedin'),
	path('dilekçehak',  views.dilekçehak, name='dilekçehak'),
	path('unvanyön',  views.unvanyön, name='unvanyön'),
	path('sinavatama',  views.sinavatama, name='sinavatama'),
    path('hukukdurus',  views.hukukdurus, name='hukukdurus'),

]
